<?php

/**
 * @file
 * Implement a family member field.
 */

/**
 * Implements hook_field_info().
 */
function mic_familymember_field_info() {
  return array(
    'mic_familymember' => array(
      'label' => t('Family Member'),
      'description' => t('This field stores family member info.'),
      'settings' => array(),
      'instance_settings' => array(),
      'default_widget' => 'mic_familymember_standard',
      'default_formatter' => 'mic_familymember_default',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function mic_familymember_field_is_empty($item, $field) {
  // Every familymember field must have at least a relationship value or it is considered
  // empty, even if it has name information.
  return empty($item['relationship']);
}

/**
 * Implements hook_field_widget_info()
 */
function mic_familymember_field_widget_info() {
  return array(
    'mic_familymember_standard' => array(
      'label' => t('Family member form'),
      'field types' => array('mic_familymember'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function mic_familymember_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'mic_familymember_standard':
      // Add the relationship, name, and instrument fields.
      $element['relationship'] = array(
        '#title' => t('Relationship'),
        '#type' => 'select',
        '#default_value' => isset($items[$delta]['relationship']) ? $items[$delta]['relationship'] : '',
        '#options' => _mic_familymember_relationship_options(),
      );
      $element['firstname'] = array(
        '#type' => 'textfield',
        '#title' => t('First Name'),
        '#default_value' => isset($items[$delta]['firstname']) ? $items[$delta]['firstname'] : '',
      );
      $element['lastname'] = array(
        '#type' => 'textfield',
        '#title' => t('Last Name'),
        '#default_value' => isset($items[$delta]['lastname']) ? $items[$delta]['lastname'] : '',
      );
      $element['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#default_value' => isset($items[$delta]['email']) ? $items[$delta]['email'] : '',
      );

      //student specific info
      $element['birthday'] = array(
        '#title' => t('Birthday'),
        '#type' => 'date_popup',
        '#date_format' => 'm/d/Y',
        '#date_year_range' => '-100:0',
        '#default_value' => isset($items[$delta]['birthday']) ? $items[$delta]['birthday'] : '',
      );
      $element['instrument'] = array(
        '#title' => t('Instrument'),
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['instrument']) ? $items[$delta]['instrument'] : '',
      );
      break;
  }

  return $element;
}

function _mic_familymember_relationship_options() {
  $relationships = array(
    'self' => 'Self',
    'child' => 'Child',
    'parent' => 'Parent',
    'guardian' => 'Guardian',
    'partner' => 'Partner',
    'spouse' => 'Spouse',
    'other' => 'Other',
  );

  return $relationships;
}

/**
 * Implements hook_field_formatter_info().
 */
function mic_familymember_field_formatter_info() {
  $formatters = array(
    'mic_familymember_default' => array(
      'label' => t('Default'),
      'field types' => array('mic_familymember'),
    ),
  );

  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 */
function mic_familymember_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  $settings += array(
    'entity_type' => $entity_type,
    'entity' => $entity,
  );

  switch($display['type']) {
    case 'mic_familymember_default':
      $element[] = array(
        '#theme' => 'mic_familymember_formatter',
        '#items' => $items,
        '#settings' => $settings,
      );
      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function mic_familymember_theme() {
  return array(
    'mic_familymember_formatter' => array(
      'variables' => array(
        'items' => NULL,
        'settings' => array(),
      ),
    ),
  );
}

/**
 * Returns HTML for a family member.
 *
 * @param $variables
 *
 * @ingroup themeable
 */
function theme_mic_familymember_formatter($variables) {
  $items = $variables['items'];
  $settings = $variables['settings'];
  $output = '';

  foreach ($items as $delta => $item) {
    $familymember = array();
    $familymember[] = '<strong>Relationship:</strong> ' . ucfirst($item['relationship']);
    $familymember[] = '<strong>Name:</strong> ' . $item['firstname'] . '&nbsp' . $item['lastname'];
    $date = new DateTime($item['birthday']);
    $familymember[] = '<strong>Birthday:</strong> ' . $date->format('m/d/Y');
    $familymember[] = '<strong>Email:</strong> ' . $item['email'];
    $familymember[] = '<strong>Instrument:</strong> ' . $item['instrument'];

    $output .= '<p>' . implode('<br />', $familymember) . '</p>';
  }

  return '<div class="familymembers">' . $output . '</div>';
}

function mic_commerce_is_student_callback($form, $form_state) {
  return $form['student_info'];
}