<?php
/**
 * @file
 * Custom, key-required form to create user profiles
 */

function mic_profile_menu() {
  $items = array();

  $items['add/profile'] = array(
    'title' => 'Add a New Profile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mic_profile_add_profile_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function mic_profile_add_profile_form($form, &$form_state) {
  $parameters = drupal_get_query_parameters();
  if (!isset($parameters['auth']) && ($parameters['auth'] != 'foo')) {
    return drupal_not_found();
  }

  drupal_add_css(drupal_get_path('module', 'mic_profile') . '/css/mic_profile.css', 'file');

  //name
  $form['name'] = array(
    '#type' => 'fieldset',
    '#title' => t('Name'),
    '#description' => t('Please type your name as you wish it to appear to the public including prefix/suffix as applicable.
Example:  Dr. Jonathan S. Smith'),
  );
  $form['name']['title'] = array(
    '#prefix' => '<div class="inline">',
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#size' => 15,
  );
  $form['name']['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First'),
    '#size' => 30,
    '#required' => TRUE,
  );
  $form['name']['last'] = array(
    '#type' => 'textfield',
    '#title' => t('Last'),
    '#size' => 30,
    '#required' => TRUE,
  );
  $form['name']['suffix'] = array(
    '#type' => 'textfield',
    '#title' => t('Suffix'),
    '#size' => 15,
    '#suffix' => '</div>',
  );

  //titles
  $form['titles'] = array(
    '#type' => 'textfield',
    '#title' => t('MIC Title(s)'),
    '#description' => t('Are you a department head, or Program Director?
Please indicate your faculty titles here.  If you also have an administrative role at MIC, that information will be handled elsewhere.'),
  );

  //headshot
  $form['headshot'] = array(
    '#type' => 'file',
    '#title' => t('Attach your photo here'),
    '#description' => t('Upload a file, allowed extensions: jpg, jpeg, png, gif'),
  );

  //program areas
  $form['program_areas'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Program Area(s)'),
    '#options' => mic_profile_get_taxonomy_options('program_area'),
    '#description' => t('Please select the program areas with which you are affiliated.  Only include areas for which you have been hired to teach at MIC.'),
  );

  //instrument
  $form['instrument'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Instrument(s)'),
    '#options' => mic_profile_get_taxonomy_options('instrument'),
    '#description' => t('Please select your instrument affiliations (include only the instruments for which you have been hired to teach at MIC.'),
  );

  //campus
  $form['campus'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Campus(es)'),
    '#options' => mic_profile_get_taxonomy_options('campus'),
    '#description' => t('At which MIC campus or campuses do you currently teach.'),
  );

  //education
  $form['education'] = array(
    '#type' => 'textarea',
    '#title' => t('Education'),
    '#description' => t('Please list your degrees (highest degree first).  Use abbreviations for degree type followed by college or university from with degree was received.
(e.g.  MM, Northwestern University).'),
    '#required' => TRUE,
  );

  //hire date
  $form['hire_date'] = array(
    '#type' => 'date_popup',
    '#title' => t('MIC Hire Date'),
    '#date_label_position' => 'none',
    '#date_type' => DATE_DATETIME,
    '#date_timezone' => date_default_timezone(),
    '#date_format' => 'm/d/Y',
    '#date_year_range' => '-20:+0',
    '#required' => TRUE,
  );

  //study
  $form['study'] = array(
    '#type' => 'textarea',
    '#title' => t('With whom did you study?'),
    '#required' => TRUE,
  );

  //awards
  $form['teaching'] = array(
    '#type' => 'textarea',
    '#title' => t('Professional Affiliations & Activities'),
  );

  //teaching
  $form['teaching'] = array(
    '#type' => 'textarea',
    '#title' => t('Basic Teaching Philosophy or Special Music Interests/Specialties'),
    '#required' => TRUE,
  );

  //interests
  $form['interests'] = array(
    '#type' => 'textarea',
    '#title' => t('Interests Outside of Music'),
    '#description' => t('Musicians are multi-faceted!  Tell us about your "facets" !  Are you writing a novel?  Are you a marathon runner? Do you also play nose flute???'),
  );

  //quote
  $form['quote'] = array(
    '#type' => 'textarea',
    '#title' => t('Favorite Quote'),
    '#description' => t('Optional.  We are collecting favorite music / inspirational quotes for use on the new website.'),
  );

  //practice
  $form['practice'] = array(
    '#type' => 'textarea',
    '#title' => t('Favorite Practice Tip'),
    '#description' => t('Optional.  We are collecting tips to rotate through appropriate areas of the website.  Your tip will be properly credited.'),
  );

  //composer
  $form['composer'] = array(
    '#type' => 'textarea',
    '#title' => t('Favorite Composer or piece to play'),
    '#description' => t('Optional.  We are collecting bits of trivia for the new website.'),
  );

  //personal
  $form['personal'] = array(
    '#type' => 'textarea',
    '#title' => t('Favorite Personal Musical Moment'),
    '#description' => t('Last one!  Again, this is optional.  We are collecting interesting info for our website/facebook, etc.  Please share your favorite musical moment...going to hear the symphony for the first time...performing at Carnegie Hall...debuting your new composition...meeting a musical hero.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function mic_profile_get_taxonomy_options($vocabulary_machine_name) {
  $vocab = taxonomy_vocabulary_machine_name_load($vocabulary_machine_name);
  $terms = taxonomy_get_tree($vocab->vid);
  $options = array();
  foreach ($terms as $term) {
    $options[$term->tid] = $term->name;
  }

  return $options;
}