<?php
/**
 * @file
 * Custom, key-required form to create user profiles
 */

define(MIC_PROFILE_PASS, crypt('micadmin', 'salt'));

/**
 * Implements hook_menu
 *
 * @return array
 */
function mic_profile_menu() {
  $items = array();

  $items['add/profile'] = array(
    'title' => 'Add a New Profile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mic_profile_add_profile_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'mic_profile.form.inc',
  );
  $items['add/profile/%node/thankyou'] = array(
    'title' => 'Thank-you for Adding a Profile',
    'page callback' => 'mic_profile_add_profile_thankyou',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_block_info()
 *
 * @return array
 */
function mic_profile_block_info() {
  $blocks['mic_profile_instrument'] = array(
    'info' => t('MIC: List of Profiles by Instrument'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}


function mic_profile_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'mic_profile_instrument':
      $block['subject'] = '';
      $block['content'] = mic_profile_instrument();
      break;
  }
  return $block;
}

function mic_profile_instrument() {
  $node = menu_get_object('node');
  $output = array();
  if (isset($node) && is_object($node)) {
    //grab instrument
    $instruments = field_get_items('node', $node, 'field_standard_instruments');
    if (is_array($instruments)) {
      foreach ($instruments as $instrument) {
        $term_name = $instrument['taxonomy_term']->name;
        $terms = mic_profile_get_taxonomy('instrument', $term_name);
        foreach ($terms as $term) {
          $output[] = '<strong>' . $term->name . '</strong>';
          $profile = mic_profile_get_profiles_by_taxonomy($term->tid);
          if ($profile) {
            $node = node_load(array_keys($profile));
            $output[] = l($node->title, 'node/' . $profile->nid);
          }
        }

      }
    }
  }
  return implode("<br />", $output);
}

/**
 * Thank-you message
 *
 * @param $node
 * @return array
 */
function mic_profile_add_profile_thankyou($node) {
  drupal_set_message('Thank-you. Your profile has been created.');
  return node_view($node, 'full');
}

/**
 * Return list of taxonomy terms
 *
 * @param $vocabulary_machine_name
 * @param null $term_name
 * @return array
 */
function mic_profile_get_taxonomy_options($vocabulary_machine_name, $term_name = NULL) {
  $terms = mic_profile_get_taxonomy($vocabulary_machine_name, $term_name);
  $options = array();
  foreach ($terms as $term) {
    $options[$term->tid] = $term->name;
  }

  return $options;
}

/**
 * Auth check function
 *
 * @param $phrase
 * @return bool
 */
function mic_profile_salt($phrase) {
  return (MIC_PROFILE_PASS == $phrase) ? TRUE : FALSE;
}

/**
 * Helper to lookup if profile with name already exists
 * Returns the nid if found
 *
 * @param string $name
 * @return int
 */
function mic_profile_namelookup($name) {
  $result = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('title', $name)
    ->execute()
    ->fetchCol();
  return reset($result);
}

function mic_profile_get_taxonomy($vocabulary_machine_name, $term_name = NULL) {
  $term = (isset($term_name)) ? taxonomy_get_term_by_name($term_name, $vocabulary_machine_name) : NULL;
  $parent = (isset($term)) ? array_keys($term) : 0;
  $parent = (is_array($parent)) ? reset($parent) : $parent;
  $vocab = taxonomy_vocabulary_machine_name_load($vocabulary_machine_name);
  $terms = taxonomy_get_tree($vocab->vid, $parent);
  return $terms;
}

function mic_profile_get_profiles_by_taxonomy($tid) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'profile')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_profile_instruments', 'tid', $tid)
    ->execute();

  return reset($result);
}