<?php
/**
 * @file Wufoo import stuff
 */

define('WUFOO_API', 'AICY-DMZE-OMJ5-0SJ7');
define('WUFOO_SUBDOMAIN', 'musicinst');
//https://AICY-DMZE-OMJ5-0SJ7:musicinst@wufooapi.wufoo.com/api/v3/forms.json?pretty=true

/**
 * Implements hook_menu()
 *
 * @return array
 */
function mic_wufoo_menu() {
  $items = array();

  $items['wufoo/profiles'] = array(
		'title' => 'Wufoo Import Profiles',
		'page callback' => 'drupal_get_form',
    'page arguments' => array('mic_wufoo_profiles_form'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_CALLBACK,
		'file' => 'mic_wufoo.profiles.inc',
	);

	return $items;
}

/**
 * Implementes hook_admin_paths()
 *
 * @return array
 */
function mic_wufoo_admin_paths() {
  $paths = array(
    'wufoo/profiles' => TRUE,
  );
  return $paths;
}

/**
 * Helper to lookup taxonomy based on a string
 *
 * @param string $string
 * @return int
 */
function _mic_wufoo_taxonomy_lookup($string) {
  $instrument = taxonomy_vocabulary_machine_name_load('instrument');
  $program = taxonomy_vocabulary_machine_name_load('program_area');

  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('name', $string)
    ->propertyCondition('vid', array($instrument->vid, $program->vid), 'IN')
    ->execute();
  $term = isset($result['taxonomy_term']) ? reset($result['taxonomy_term']) : new stdClass();
  return (isset($term->tid)) ? $term->tid : NULL;
}

/**
 * Helper to see if this a proper field to import
 *
 * @param string $name
 * @return bool
 */
function _mic_wufoo_fieldcheck($name) {
  return is_numeric(strpos($name, 'Field')) ? TRUE : FALSE;

}