<?php
/**
 * @file
 * MIC Private Registration
 */

/**
 * Implements hook_menu().
 *
 * @return array
 */
function mic_private_menu() {
  $items = array();
  $items['private-registration'] = array(
    'title' => t('2015 - 2016 Private Instruction Registration Form'),
    'description' => t('Register for private instruction.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mic_private_private_registration_form'),
    'access arguments' => array('access content'),
    'file' => 'mic_private.form.inc',
  );

  return $items;
}

/**
 * Alter the Pay a Bill form for Private Instruction.
 *
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param $form_state
 */
function mic_private_form_commerce_cart_add_to_cart_form_325_alter(&$form, &$form_state) {
  $params = drupal_get_query_parameters();
  if (isset($params['hash'])) {
    $data = db_query("SELECT micp.data FROM {mic_private} micp WHERE hash = :hash", array(
      ':hash' => $params['hash'],
    ))->fetchField();
    $data = unserialize($data);
    $family_record = !empty($data['values']['family_record']) ? $data['values']['family_record'] : 00000;
    $form['line_item_fields']['field_billpay_acct'][LANGUAGE_NONE][0]['value']['#default_value'] = $family_record;
    $form['line_item_fields']['field_billpay_acct'][LANGUAGE_NONE][0]['value']['#attributes'] = array('readonly' => 'readonly');

    // Format output
    $info = array();
    $skip = array(
      'submit',
      'form_build_id',
      'form_id',
      'form_token',
      'op',
    );
    $taxonomy = array('campus', 'pi_instrument');
    foreach ($data['values'] as $key => $value) {
      if (!in_array($key, $skip)) {
        if (in_array($key, $taxonomy)) {
          $term = taxonomy_term_load($value);
          $value = $term->name;
        }
        elseif (in_array($key, array('suzuki', 'musicianship', 'instructor'))) {
          $node = node_load($value);
          $value = $node->title;
        }
        if (($value != '- Select -') && (!empty($value)) && ($value != 'No')) {
          // Custom displays
          switch ($key) {
            case 'multiple':
              $key = $key . ' (-$25 sibling discount)';
              break;

            case 'adult_discount':
              $key = $key . ' (20% discount)';
              break;

            case 'senior_discount':
              $key = $key . ' (15% discount)';
              break;

            case 'student_type':
              $show_fee = ('new' == $value) ? TRUE : FALSE;
              if (time() > 1433739600) {
                $show_fee = TRUE;
              }
              break;
          }

          $info[] = filter_xss(ucfirst($key)) . ': ' . filter_xss($value);
        }
      }
    }
    $info[] = "\n";
    $info[] = 'Lesson Total: $' . filter_xss($data['lesson_total']);
    if (isset($data['musicianship_fee'])) {
      $info[] = 'Musicianship Fee: $' . filter_xss($data['musicianship_fee']);
    }
    if (isset($show_fee) && (TRUE == $show_fee)) {
      $info[] = 'Registration Fee: $25.00';
    }
    $info[] = "\n";

    $info[] = 'Sub-total: $' . filter_xss($data['calculated_total']);

    $form['line_item_fields']['field_billpay_info'][LANGUAGE_NONE][0]['value']['#title'] = 'Submitted Details';
    $form['line_item_fields']['field_billpay_info'][LANGUAGE_NONE][0]['value']['#default_value'] = implode("\n", $info);
    $form['line_item_fields']['field_billpay_info'][LANGUAGE_NONE][0]['value']['#attributes'] = array('readonly' => 'readonly');
    $form['line_item_fields']['field_billpay_info'][LANGUAGE_NONE][0]['value']['#rows'] = 30;
    $form['line_item_fields']['field_billpay_amount'][LANGUAGE_NONE][0]['value']['#default_value'] = $data['total'];
    $form['line_item_fields']['field_billpay_amount'][LANGUAGE_NONE][0]['value']['#attributes'] = array('readonly' => 'readonly');

    // Destroy cookie
    setcookie("mic-private-instruction", "", time() - 3600);
  }

}